# Generated by Django 2.2 on 2020-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200926_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tech', 'Бытовая техника'), ('food', 'Еда'), ('other', 'Разное'), ('tools', 'Инструменты')], default='other', max_length=40, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(3, 3), (5, 5), (4, 4), (2, 2), (1, 1)], verbose_name='Оценка'),
        ),
    ]
